version: "3.8"

services:
  mjpg-streamer:
    build: .
    container_name: mjpg-streamer
    restart: always
    privileged: true
    devices:
      - /dev/video0:/dev/video0
    environment:
      MJPG_STREAMER_INPUT: "-i input_uvc.so -y -n -r 1920x1080 -f 30 -d /dev/video0"
      MJPG_STREAMER_OUTPUT: "-o output_http.so -w /opt/mjpg-streamer/mjpg-streamer-experimental/www -p 8080"
    ports:
      - "8080:8080"
