FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y \
    build-essential git libjpeg-dev imagemagick cmake \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /opt
RUN git clone https://github.com/jacksonliam/mjpg-streamer.git
WORKDIR /opt/mjpg-streamer/mjpg-streamer-experimental
RUN make

ENTRYPOINT ["./mjpg_streamer"]
